### ISSUE TITLE
table_name overrides don't carry over properly

### ISSUE THREAD

**Issue by JohnCoogan** [thestorefront/FastAPI#1]
Because the code uses the `tableize` method provided by activesupport, it is not possible for FastAPI to work with tables that do not follow the traditional Rails naming conventions. Instead of generating the table name from the class name, the table name should be accessed from the `table_name` attribute of the class, which is available by default and can be overridden very easily in any given model.

```ruby
# current table name code used 6 times
self_string_table = @model.to_s.tableize

# calls this rails code
# File activesupport/lib/active_support/inflector/methods.rb, line 143
def tableize(class_name)
  pluralize(underscore(class_name))
end

# which does not pay attention to active_record configs
config.active_record.pluralize_table_names = false

# using the table_name attribute yields a more consistent result and can be overridden in models as necessary
model.table_name
```

[Example on line 760](https://github.com/thestorefront/FastAPI/blob/master/lib/fastapi.rb#L760)

I have already fixed this in my project, but am hesitant to issue a pull request until I have tested this more thoroughly. Let me know what you think.

**Comment by TrevorS** [comment]
Hello @JohnCoogan, it's been a while since you created this issue, but I did want to let you know that custom table names, primary keys, and foreign keys are now supported by FastAPI and will be included in the next release.

Thanks!

**Comment by JohnCoogan** [comment]
Awesome, thanks!

--
John Coogan
626-272-1760
